version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/scan"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      backend:
        condition: service_healthy
